name: Go E2E Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: E2E Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: Install Dependencies
        run: |
          chmod +x ./setup.sh
          ./setup.sh
          go mod tidy

      - name: Run Tests
        run: go test -v ./e2e_test/...
