name: Go Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: Install Dependencies
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Check goimports
        run: |
          if [ -n "$(goimports -l .)" ]; then
            exit 1
          fi
