name: Go Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: Install Dependencies
        run: |
          chmod +x ./setup.sh
          ./setup.sh
          go mod tidy

      - name: Check go vet
        run: go vet ./...
