name: Go Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Dependencies
        run: |
          chmod +x ./setup.sh
          ./setup.sh
          go mod tidy

      - name: Run Tests
        run: |
          go test -v .
          go test -v ./ahttp
